### ISSUE TITLE
错别字：控制面板-个性化-主题-控件主题，写成空间主题。模块和板块要统一，要使用模块都使用模块，上一句是模块，下一句就是板块

### ISSUE THREAD

**Issue by Liang-zy** [lmq3342xja/kylin-user-guide#43]
![2020-04-16 20-27-30屏幕截图](https://user-images.githubusercontent.com/39893452/79456439-1d2d3700-8021-11ea-8c6c-2ba36d4e9b57.png)
![2020-04-16 20-27-36屏幕截图](https://user-images.githubusercontent.com/39893452/79456456-23231800-8021-11ea-99a2-370d160bb8b8.png)

**Comment by microcaMI** [comment]
定义：
1.模块：模块位置在控制面板左边，如：二级标题“个性化”、“网络”、“账户”等
2.板块：板块位置在控制面板模块内部，如：二级标题“个性化”模块中，三级标题“主题”中的“主题模式”、“图标主题”、“空间主题”等
注意：
二级标题和三级标题的字号以及色号都是不一样的，请再次阅读其详细分类。

**Comment by Liang-zy** [comment]
那就是写错了：个性化设置提供了主题模式、图标模式、空间主题、光标主题、效果设置五个模块。这写是不是主题下的五个板块？   是不是应该是个性化设置提供了主题、背景、锁屏、屏保、字体五个模块。    还有体验计划写成板块了

**Comment by microcaMI** [comment]
> 
> 
> 那就是写错了：个性化设置提供了主题模式、图标模式、空间主题、光标主题、效果设置五个模块。这写是不是主题下的五个板块？ 是不是应该是个性化设置提供了主题、背景、锁屏、屏保、字体五个模块。 还有体验计划写成板块了

嗯，内容错了，定义没错，最新版本里面已经集成了~
请继续帮忙校对~

**Comment by Liang-zy** [comment]
![image](https://user-images.githubusercontent.com/39893452/84615883-c5b22700-aefc-11ea-9d4a-57313dd3ff36.png)
体验计划应该为模块

**Comment by microcaMI** [comment]
已更新

**Comment by Liang-zy** [comment]
20200702 test passed
